# Generated by Django 5.2.1 on 2025-06-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_delete_itineraryversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRateCache',
        ),
        migrations.DeleteModel(
            name='WeatherCache',
        ),
    ]
