# Generated by Django 5.2.1 on 2025-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_exchangeratecache_weathercache_itineraryversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
