# Generated by Django 5.2.1 on 2025-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_itinerary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='visit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
