# Generated by Django 5.2.1 on 2025-06-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_location_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
